include: package:very_good_analysis/analysis_options.4.0.0.yaml

linter:
  rules:
    file_names: false
    sort_pub_dependencies: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
