name: winmeet_mobile
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  # State management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0

  # Networking
  dio: ^5.0.3
  pretty_dio_logger: ^1.1.1

  # Caching
  shared_preferences: ^2.1.0

  # Routing
  auto_route: ^5.0.4

  # Dependency injection
  get_it: ^7.2.0
  injectable: ^2.1.0

  # Data class generation
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # Functional programming
  dartz: ^0.10.1

  # UI
  table_calendar: ^3.0.8
  cupertino_icons: ^1.0.2
  omni_datetime_picker: ^1.0.1

  # Utility
  intl: ^0.17.0
  jwt_decode: ^0.3.1
  flutter_svg: ^2.0.4
  path_provider: ^2.0.12
  
  # Splash screen
  flutter_native_splash: ^2.2.18

  # Packages
  form_inputs:
    path: packages/form_inputs

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code gen
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.4
  auto_route_generator: ^5.0.3

  # Linter
  very_good_analysis: ^4.0.0
  # Launcher Icons
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#6750A4"
  # Padding 8%
  adaptive_icon_foreground: "assets/logo/logo_foreground.png"

flutter_native_splash:
  android: true
  ios: true
  android12: true
  color: "#6750A4"
  image: "assets/logo/logo.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/svg/
    